# Generated by Django 4.0.4 on 2022-05-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Зарплата'),
        ),
    ]
